
spring:

  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/seefood?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true}
    username: ${DATASOURCE_USERNAME:username}
    password: ${DATASOURCE_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    properties:
      default_batch_fetch_size: 100
      hibernate:
        format_sql: true
#  sql:
#    init:
#      mode: ALWAYS
#      schema-locations: classpath:sql/schema.sql
#      data-locations: classpath:sql/data.sql