spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/springbatch?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:2848}

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    properties:
      default_batch_fetch_size: 100
      hibernate:
        format_sql: true