spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

# ?? ????? ??? enable-logging ? false? ?? ??
#decorator:
#  datasource:
#    p6spy:
#      enable-logging: true

logging.level:
  org.hibernate.SQL: debug
  org.bibernate.type: trace